### ISSUE TITLE
failed in converting 2nd argument `b' of _flapack.dpotrs to C/Fortran array

### ISSUE THREAD

**Issue by poojitharamachandra** [amzn/emukit#143] opened 2018-12-09 15:48 UTC
Y_init = np.array(Y_init,ndmin=2,order='F')
X_init = np.array(X_init,ndmin=2)
import GPy
from emukit.model_wrappers.gpy_model_wrappers import GPyModelWrapper
from emukit.bayesian_optimization.acquisitions import ExpectedImprovement
from emukit.core.optimization import AcquisitionOptimizer
kernel = GPy.kern.Matern52(X_init.shape[1], ARD=True)
gp = GPyModelWrapper(GPy.models.GPRegression(X_init, Y_init, kernel, noise_var=1e-10))
**gives error:~\Anaconda3\lib\site-packages\gpy-1.9.6-py3.6-win-amd64.egg\GPy\util\linalg.py in dpotrs(A, B, lower) :
error: failed in converting 2nd argument `b' of _flapack.dpotrs to C/Fortran array**
X_init = [[ -5.5589826 384.25838475 751.38855262 164.3880191 1007.11674873]
[ -1.08051782 382.02255555 200.88970441 268.82545867 588.76049642]]
Y_init= [[0.37135806 0.31397561]]

**Comment by aaronkl** [comment] 2018-12-10 09:56
Is there a particular reason why your array has to be in 'F' order? Could you try to use the default 'K' order?

**Comment by poojitharamachandra** [comment] 2018-12-10 11:02
>           Is there a particular reason why your array has to be in 'F' order? Could you try to use the default 'K' order?

its the same with default 'K' order

**Comment by aaronkl** [comment] 2018-12-10 12:30
could you provide more information? What is X_init and Y_init before you convert it to an np.array

**Comment by poojitharamachandra** [comment] 2018-12-10 12:35
before converting

[[ -4.64182228 360.55534607 846.68851669 317.06098207 217.4058002 ]
 [ -4.02261383 362.61479649 560.03820332 357.75521425 423.61642425]]
[0.27079263373911405, 0.2587080814016096]


after converting


[[ -4.64182228 360.55534607 846.68851669 317.06098207 217.4058002 ]
 [ -4.02261383 362.61479649 560.03820332 357.75521425 423.61642425]]
[[0.27079263 0.25870808]]

**Comment by aaronkl** [comment] 2018-12-10 13:16
are they both lists? If so what happens if you simply do X_init = np.array(X_init), Y_init = np.array(Y_init)[:, None]

**Comment by poojitharamachandra** [comment] 2018-12-10 13:33
The ndim is set to 1 by default and it fails again

Regards,
Poojitha Ramachandra

**Comment by aaronkl** [comment] 2018-12-10 13:42
I think we should take this offline. Could you drop by at tomorrow's Q/A session?

**Comment by poojitharamachandra** [comment] 2018-12-10 13:43
Sure...will do.. thanks

Regards,
Poojitha Ramachandra

**Comment by poojitharamachandra** [comment] 2018-12-10 20:06
yes! if I changed the Y_init manually to a column vector, it works! Could you please give me a hint on how to convert a list to column vector ?

Thank you

>           I think that the problem is that Y_init needs to be a column vector and X_init an nxp array where n is the number of rows and p the number of variables.

yes! if I changed the Y_init manually to a column vector, it works! Could you please give me a hint on how to convert a list to column vector ?

Thank you

**Comment by poojitharamachandra** [comment] 2018-12-10 20:13
I tried  Y_init = np.reshape(Y_init,(-1,1)) and there is no error . Hope  this is correct

**Comment by marpulli** [comment] 2018-12-11 13:12
Issue seems to be resolved, closing.

**Closed by marpulli** 2018-12-11 13:12 UTC

**Comment by lawrennd** [comment] 2020-11-06 09:54
I just had the same issue. It was a dimension mismatch, but the error message is super unclear. 

For me it was a problem that arises in GPy.models.GPRegression() when X and y have different numbers of rows and the model tries to initialise and fails in the dpotrs call. 

Perhaps we should raise an issue on GPy to do a dimension check??

**Comment by apaleyes** [comment] 2020-11-06 10:19
Thanks @lawrennd ! Yes, raising this with GPy feels appropriate. Do you happen to still have the code that reproduces it?

**Comment by lawrennd** [comment] 2020-11-08 21:20
Yep, here's a (I think minimal) code snippet.

import GPy
import numpy as np
X = np.random.randn(100, 3) # number of data points is 100
y = np.random.randn(50, 1) # number of data points is 50
model = GPy.models.GPRegression(X, y)

**Comment by apaleyes** [comment] 2020-11-08 23:14
Thanks Neil, very helpful. Bang: https://github.com/SheffieldML/GPy/issues/871
